--- copilot_review.lua — review (and edit) Copilot CLI's proposed file changes
--- in Neovim before they are applied.
---
--- Standalone: nothing here touches copilot_cli.lua beyond calling its public
--- instances() for the attach picker. Remove this file, its after/plugin stub
--- and run :CopilotReviewUninstall to revert completely.
---
--- Mechanism: a `preToolUse` hook fires before every tool call. Its documented
--- output can rewrite the pending call:
---   { permissionDecision, modifiedArgs, additionalContext }
--- so your edits replace what the agent proposed, and additionalContext tells
--- the agent what you changed — it isn't left guessing why the file differs.
---
--- The hook is inert unless you've attached: with no marker file for that
--- session it exits immediately, so unattached sessions are unaffected.

local M = {}

local IPC = vim.fs.normalize(vim.fn.expand("$LOCALAPPDATA") .. "/copilot-nvim-review")
local HOOK_JSON = vim.fs.normalize(vim.fn.expand("~/.copilot/hooks/nvim-review.json"))
local HOOK_PS1 = IPC .. "/hook.ps1"

--- Tools worth intercepting. Everything else falls straight through.
local REVIEWED_TOOLS = { edit = true, create = true }

M.config = {
  --- Hook budget. The script self-limits just under this; on timeout it
  --- produces no output and the CLI falls back to its normal prompt.
  timeout_sec = 600,
  poll_ms = 250,
}

--------------------------------------------------------------------------------
-- Hook script
--------------------------------------------------------------------------------

local HOOK_SOURCE = [==[
# Auto-generated by copilot_review.lua. Safe to delete; :CopilotReviewInstall rewrites it.
$ErrorActionPreference = "Stop"
$IPC = Join-Path $env:LOCALAPPDATA "copilot-nvim-review"

try { $raw = [Console]::In.ReadToEnd() } catch { exit 0 }
if (-not $raw) { exit 0 }
try { $o = $raw | ConvertFrom-Json } catch { exit 0 }

$tool = $o.toolName
if ($tool -ne "edit" -and $tool -ne "create") { exit 0 }

# Inert unless an attached marker matches this session. One copilot.exe can
# hold several sessions (restore/fork), so match on cwd as well as sessionId.
$attachDir = Join-Path $IPC "attached"
if (-not (Test-Path $attachDir)) { exit 0 }
$isAttached = $false
function Norm-Dir($p) { if (-not $p) { return $null }; return ($p -replace '\\','/').TrimEnd('/').ToLower() }
$reqCwd = Norm-Dir $o.cwd
foreach ($m in (Get-ChildItem $attachDir -Filter *.json -ErrorAction SilentlyContinue)) {
  try { $mk = [System.IO.File]::ReadAllText($m.FullName) | ConvertFrom-Json } catch { continue }
  # A marker whose Neovim is gone would otherwise block every edit until the
  # hook times out. Treat it as stale and remove it.
  if ($mk.pid) {
    if (-not (Get-Process -Id $mk.pid -ErrorAction SilentlyContinue)) {
      Remove-Item $m.FullName -Force -ErrorAction SilentlyContinue
      continue
    }
  }
  if ($mk.session -and $mk.session -eq $o.sessionId) { $isAttached = $true; break }
  $mkCwd = Norm-Dir $mk.cwd
  if ($mkCwd -and $reqCwd -and $mkCwd -eq $reqCwd) { $isAttached = $true; break }
}
if (-not $isAttached) { exit 0 }

$id = [guid]::NewGuid().ToString()
$reqDir = Join-Path $IPC "req"
$resDir = Join-Path $IPC "res"
New-Item -ItemType Directory -Force -Path $reqDir, $resDir | Out-Null

$req = @{
  id        = $id
  sessionId = $o.sessionId
  cwd       = $o.cwd
  toolName  = $tool
  toolArgs  = $o.toolArgs
} | ConvertTo-Json -Depth 20 -Compress

$reqFile = Join-Path $reqDir "$id.json"
$tmp = "$reqFile.tmp"
[System.IO.File]::WriteAllText($tmp, $req, (New-Object System.Text.UTF8Encoding($false)))
Move-Item $tmp $reqFile -Force

'{"type":"progress","message":"Awaiting review in Neovim...","temporary":true}'

$resFile = Join-Path $resDir "$id.json"
$deadline = (Get-Date).AddSeconds(TIMEOUT_PLACEHOLDER)
$verdict = $null
while ((Get-Date) -lt $deadline) {
  if (Test-Path $resFile) {
    try {
      $verdict = [System.IO.File]::ReadAllText($resFile) | ConvertFrom-Json
      break
    } catch { Start-Sleep -Milliseconds 60 }   # partially written; retry
  }
  Start-Sleep -Milliseconds 150
}

Remove-Item $reqFile, $resFile -Force -ErrorAction SilentlyContinue

# No verdict (Neovim gone, or user took too long): emit nothing so the CLI
# falls back to its normal permission flow.
if (-not $verdict) { exit 0 }

switch ($verdict.action) {
  "allow"  { @{ permissionDecision = "allow" } | ConvertTo-Json -Depth 5 -Compress }
  "deny"   {
    $r = if ($verdict.reason) { $verdict.reason } else { "Rejected by the user in Neovim." }
    @{ permissionDecision = "deny"; permissionDecisionReason = $r } | ConvertTo-Json -Depth 5 -Compress
  }
  "modify" {
    $note = if ($verdict.note) { $verdict.note } else { "The user edited this change in Neovim before it was applied." }
    @{
      permissionDecision = "allow"
      modifiedArgs       = $verdict.args
      additionalContext  = $note
    } | ConvertTo-Json -Depth 20 -Compress
  }
  default  { }
}
exit 0
]==]

--------------------------------------------------------------------------------
-- Install / uninstall
--------------------------------------------------------------------------------

local function write_file(path, text)
  vim.fn.mkdir(vim.fs.dirname(path), "p")
  local fd = assert(io.open(path, "wb"))
  fd:write(text)
  fd:close()
end

local function read_file(path)
  local fd = io.open(path, "rb")
  if not fd then
    return nil
  end
  local t = fd:read("*a")
  fd:close()
  return t
end

--- Register the hook with Copilot CLI. Only needed once (and after upgrades).
function M.install()
  vim.fn.mkdir(IPC .. "/attached", "p")
  vim.fn.mkdir(IPC .. "/req", "p")
  vim.fn.mkdir(IPC .. "/res", "p")

  -- Self-limit under the CLI's own budget so we lose the race, not the CLI.
  local script = HOOK_SOURCE:gsub("TIMEOUT_PLACEHOLDER", tostring(M.config.timeout_sec - 30))
  write_file(HOOK_PS1, script)

  write_file(
    HOOK_JSON,
    vim.json.encode({
      version = 1,
      hooks = {
        preToolUse = {
          {
            type = "command",
            powershell = 'pwsh -NoProfile -File "' .. HOOK_PS1:gsub("/", "\\") .. '"',
            timeoutSec = M.config.timeout_sec,
          },
        },
      },
    })
  )
  vim.notify("copilot_review: hook installed -> " .. HOOK_JSON .. "\nRestart Copilot CLI sessions to pick it up.")
end

--- Remove the hook entirely.
function M.uninstall()
  M.detach()
  vim.fn.delete(HOOK_JSON)
  vim.fn.delete(HOOK_PS1)
  vim.notify("copilot_review: hook uninstalled")
end

function M.installed()
  return vim.uv.fs_stat(HOOK_JSON) ~= nil
end

--------------------------------------------------------------------------------
-- Attach / detach
--------------------------------------------------------------------------------

local attached = nil ---@type { session: string, cwd: string?, file: string }?
local timer = nil
local pending = {} ---@type table<string, boolean> requests already being shown
local active = nil

local poll -- fwd decl

--- Follow a session: intercept its edits for review.
---@param session string? session uuid; prompts when omitted
---@param cwd string? working directory to match as well (more robust than the id alone)
function M.attach(session, cwd)
  if not M.installed() then
    vim.notify("copilot_review: hook not installed; run :CopilotReviewInstall first", vim.log.levels.ERROR)
    return
  end

  local function go(id, dir, tag)
    if attached then
      M.detach()
    end
    vim.fn.mkdir(IPC .. "/attached", "p")
    local file = IPC .. "/attached/" .. vim.fn.getpid() .. ".json"
    write_file(file, vim.json.encode({ session = id, cwd = dir, pid = vim.fn.getpid(), at = os.time() }))
    attached = { session = id, cwd = dir, file = file }

    timer = vim.uv.new_timer()
    timer:start(M.config.poll_ms, M.config.poll_ms, vim.schedule_wrap(poll))
    vim.notify("copilot_review: attached to " .. (tag or id or dir or "?"))
  end

  if session or cwd then
    return go(session, cwd)
  end

  local ok, cli = pcall(require, "copilot_cli")
  if not ok then
    vim.notify("copilot_review: pass a session id (copilot_cli not available)", vim.log.levels.ERROR)
    return
  end
  local list = cli.instances()
  if #list == 0 then
    vim.notify("copilot_review: no running Copilot CLI instance", vim.log.levels.ERROR)
    return
  end
  if #list == 1 then
    return go(list[1].session, list[1].cwd, list[1].repository or list[1].cwd)
  end
  vim.ui.select(list, {
    prompt = "Attach review to:",
    format_item = function(i)
      return (i.repository or vim.fs.basename(i.cwd)) .. " · pid " .. i.pid
    end,
  }, function(choice)
    if choice then
      go(choice.session, choice.cwd, choice.repository or choice.cwd)
    end
  end)
end

--- Stop intercepting. The hook goes inert immediately.
function M.detach()
  if attached then
    vim.fn.delete(attached.file)
    attached = nil
  end
  if timer and not timer:is_closing() then
    timer:stop()
    timer:close()
  end
  timer = nil
  pending = {}
  vim.notify("copilot_review: detached")
end

function M.toggle()
  if attached then
    M.detach()
  else
    M.attach()
  end
end

function M.status()
  return attached
end

--------------------------------------------------------------------------------
-- Text <-> lines, preserving line endings so an untouched review round-trips
--------------------------------------------------------------------------------

local function to_lines(s)
  s = s or ""
  local crlf = s:find("\r\n", 1, true) ~= nil
  local trailing = s:sub(-1) == "\n"
  local norm = s:gsub("\r\n", "\n")
  local lines = vim.split(norm, "\n", { plain = true })
  if trailing then
    table.remove(lines)
  end
  return lines, { crlf = crlf, trailing = trailing }
end

local function from_lines(lines, style)
  local s = table.concat(lines, "\n")
  if style.trailing then
    s = s .. "\n"
  end
  if style.crlf then
    s = s:gsub("\n", "\r\n")
  end
  return s
end

--------------------------------------------------------------------------------
-- Review UI
--------------------------------------------------------------------------------

local function respond(req, verdict)
  vim.fn.mkdir(IPC .. "/res", "p")
  local path = IPC .. "/res/" .. req.id .. ".json"
  -- Write then rename so the hook can't read a half-written file.
  write_file(path .. ".tmp", vim.json.encode(verdict))
  os.rename(path .. ".tmp", path)
  -- Drop the request so a failed review can't be picked up again in a loop.
  vim.fn.delete(IPC .. "/req/" .. req.id .. ".json")
  active = nil
end

---@param req table decoded request from the hook
local function review(req)
  local args = req.toolArgs or {}
  local is_edit = req.toolName == "edit"
  local path = args.path or ""
  local fpath = vim.fs.normalize(path)

  -- Whole-file view: read what's on disk and apply the agent's change to a copy,
  -- so you review the file as it would end up rather than a bare hunk.
  local original_full = read_file(path) or ""
  local proposed_full, located
  if is_edit then
    local s, e = original_full:find(args.old_str or "", 1, true)
    if s and (args.old_str or "") ~= "" then
      proposed_full = original_full:sub(1, s - 1) .. (args.new_str or "") .. original_full:sub(e + 1)
      located = true
    else
      -- old_str no longer matches the file (agent working from stale content).
      proposed_full = original_full
      located = false
    end
  else
    proposed_full = args.file_text or ""
    located = true
  end

  local prop_lines, style = to_lines(proposed_full)
  local rel = vim.fn.fnamemodify(path, ":t")
  local tag = req.id:sub(1, 8)

  -- Show the real file in the window you're already in.
  local fwin = vim.api.nvim_get_current_win()
  local ok_edit = pcall(vim.cmd, "edit " .. vim.fn.fnameescape(fpath))
  if not ok_edit then
    -- Current buffer refused to be replaced (unsaved changes); use a new tab.
    pcall(vim.cmd, "tabnew " .. vim.fn.fnameescape(fpath))
    fwin = vim.api.nvim_get_current_win()
  end
  local fbuf = vim.api.nvim_get_current_buf()

  -- Proposed content to the right, editable. What you leave here is applied.
  vim.cmd("rightbelow vsplit")
  local pwin = vim.api.nvim_get_current_win()
  local pbuf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_win_set_buf(pwin, pbuf)
  vim.api.nvim_buf_set_lines(pbuf, 0, -1, false, prop_lines)
  vim.bo[pbuf].buftype = "acwrite"
  vim.bo[pbuf].bufhidden = "wipe"
  vim.api.nvim_buf_set_name(pbuf, "copilot://" .. tag .. "/proposed/" .. rel)
  vim.bo[pbuf].filetype = vim.bo[fbuf].filetype

  -- Diff the two windows.
  vim.api.nvim_set_current_win(fwin)
  vim.cmd("diffthis")
  vim.api.nvim_set_current_win(pwin)
  vim.cmd("diffthis")
  vim.cmd("normal! gg]c")

  local finished = false
  local function finish(verdict)
    if finished then
      return
    end
    finished = true
    respond(req, verdict)

    -- Leave the editor as we found it: drop diff mode, close the scratch pane.
    for _, w in ipairs({ fwin, pwin }) do
      if vim.api.nvim_win_is_valid(w) then
        vim.api.nvim_win_call(w, function()
          pcall(vim.cmd, "diffoff")
        end)
      end
    end
    if vim.api.nvim_win_is_valid(pwin) then
      pcall(vim.api.nvim_win_close, pwin, true)
    end
    if vim.api.nvim_win_is_valid(fwin) then
      pcall(vim.api.nvim_set_current_win, fwin)
    end
    -- The agent writes just after we answer; pick the change up.
    vim.defer_fn(function()
      if vim.api.nvim_buf_is_valid(fbuf) then
        vim.api.nvim_buf_call(fbuf, function()
          pcall(vim.cmd, "checktime")
        end)
      end
    end, 1200)
  end

  local function clip(s)
    s = (s or ""):gsub("\r\n", "\n")
    return #s > 1500 and (s:sub(1, 1500) .. "\n...[truncated]") or s
  end

  local function approve()
    local edited_full = from_lines(vim.api.nvim_buf_get_lines(pbuf, 0, -1, false), style)

    if edited_full == proposed_full and located then
      finish({ action = "allow" })
      vim.notify("copilot_review: approved as proposed")
      return
    end

    -- Replace the whole file: unambiguous, and it also repairs the case where
    -- the agent's old_str no longer matched what's on disk.
    local new_args = vim.deepcopy(args)
    if is_edit then
      new_args.old_str = original_full
      new_args.new_str = edited_full
    else
      new_args.file_text = edited_full
    end

    finish({
      action = "modify",
      args = new_args,
      note = table.concat({
        "The user reviewed this change in their editor and rewrote it before it was applied to " .. path .. ".",
        "",
        "YOU PROPOSED:",
        clip(is_edit and (args.new_str or "") or (args.file_text or "")),
        "",
        "WHAT WAS ACTUALLY WRITTEN (the user's version, full file):",
        clip(edited_full),
        "",
        "The user's version is authoritative. Do not revert it or re-apply your original proposal. "
          .. "Continue from the written content, and re-read the file if you need its exact state.",
      }, "\n"),
    })
    vim.notify("copilot_review: approved with your edits")
  end

  local function reject()
    vim.ui.input({ prompt = "Reason (optional): " }, function(reason)
      finish({ action = "deny", reason = (reason and reason ~= "") and reason or nil })
      vim.notify("copilot_review: rejected")
    end)
  end

  for _, buf in ipairs({ fbuf, pbuf }) do
    vim.keymap.set("n", "ga", approve, { buffer = buf, desc = "Copilot: approve change" })
    vim.keymap.set("n", "gr", reject, { buffer = buf, desc = "Copilot: reject change" })
  end
  -- :w in the proposal pane approves, which is the reflex most people have.
  vim.api.nvim_create_autocmd("BufWriteCmd", { buffer = pbuf, callback = approve })

  -- Closing the proposal pane without deciding must not hang the agent.
  vim.api.nvim_create_autocmd("BufWipeout", {
    buffer = pbuf,
    callback = function()
      if not finished then
        finished = true
        respond(req, { action = "deny", reason = "Review window closed without a decision." })
      end
    end,
  })

  vim.notify(
    ("copilot_review: %s %s%s  —  ga approve · gr reject"):format(
      req.toolName,
      rel,
      located and "" or "  [old_str no longer matches the file]"
    ),
    located and vim.log.levels.INFO or vim.log.levels.WARN
  )
end

--------------------------------------------------------------------------------
-- Poll for incoming requests
--------------------------------------------------------------------------------

local function norm_dir(p)
  return (p or ""):gsub("[\\/]+$", ""):gsub("\\", "/"):lower()
end

poll = function()
  if not attached then
    return
  end
  -- One review at a time; the hook keeps waiting for the rest.
  if active then
    return
  end

  for _, path in ipairs(vim.fn.glob(IPC .. "/req/*.json", true, true)) do
    local id = vim.fn.fnamemodify(path, ":t:r")
    if not pending[id] then
      local raw = read_file(path)
      if raw and #raw > 0 then
        local ok, req = pcall(vim.json.decode, raw)
        local mine = ok
          and req
          and req.id
          and REVIEWED_TOOLS[req.toolName]
          and (
            (attached.session and req.sessionId == attached.session)
            or (attached.cwd and norm_dir(req.cwd) == norm_dir(attached.cwd))
          )
        if mine then
          pending[id] = true
          active = id
          local ok2, err = pcall(review, req)
          if not ok2 then
            vim.notify("copilot_review: " .. tostring(err), vim.log.levels.ERROR)
            respond(req, { action = "allow" })
          end
          return
        end
      end
    end
  end
end

--------------------------------------------------------------------------------

-- Never leave a marker behind: a stale one would stall the agent on every edit.
vim.api.nvim_create_autocmd("VimLeavePre", {
  callback = function()
    if attached then
      pcall(vim.fn.delete, attached.file)
    end
  end,
})

vim.api.nvim_create_user_command("CopilotReviewInstall", function()
  M.install()
end, { desc = "Install the Copilot CLI review hook" })

vim.api.nvim_create_user_command("CopilotReviewUninstall", function()
  M.uninstall()
end, { desc = "Remove the Copilot CLI review hook" })

vim.api.nvim_create_user_command("CopilotReviewAttach", function(c)
  if c.args ~= "" then
    -- A path attaches by directory; anything else is treated as a session id.
    if vim.uv.fs_stat(c.args) then
      M.attach(nil, vim.fs.normalize(vim.fn.fnamemodify(c.args, ":p")))
    else
      M.attach(c.args)
    end
  else
    M.attach()
  end
end, { nargs = "?", complete = "dir", desc = "Attach review mode to a Copilot CLI session" })

vim.api.nvim_create_user_command("CopilotReviewDetach", function()
  M.detach()
end, { desc = "Detach review mode" })

vim.api.nvim_create_user_command("CopilotReviewToggle", function()
  M.toggle()
end, { desc = "Toggle review mode" })

vim.api.nvim_create_user_command("CopilotReviewStatus", function()
  local a = attached
  vim.notify(
    "copilot_review: hook "
      .. (M.installed() and "installed" or "NOT installed")
      .. ", "
      .. (a and ("attached to " .. (a.session or "?") .. " @ " .. (a.cwd or "?")) or "detached")
  )
end, { desc = "Show review mode status" })

return M
