local tree_cb = require'nvim-tree.config'.nvim_tree_callback
-- Old
--vim.g.nvim_tree_bindings = {
  --["l"]              = tree_cb("edit"),
  --["o"]              = tree_cb("edit"),
  --["<2-LeftMouse>"]  = tree_cb("edit"),
  --["<2-RightMouse>"] = tree_cb("cd"),
  --["<CR>"]           = tree_cb("cd"),
  --["<C-v>"]          = tree_cb("vsplit"),
  --["<C-h>"]          = tree_cb("split"),
  --["<C-t>"]          = tree_cb("tabnew"),
  --["h"]              = tree_cb("close_node"),
  --["<S-CR>"]         = tree_cb("close_node"),
  --["<Tab>"]          = tree_cb("preview"),
  --["I"]              = tree_cb("toggle_ignored"),
  --["z"]              = tree_cb("toggle_dotfiles"),
  --["R"]              = tree_cb("refresh"),
  --["a"]              = tree_cb("create"),
  --["d"]              = tree_cb("remove"),
  --["r"]              = tree_cb("rename"),
  --["<C-r>"]          = tree_cb("full_rename"),
  --["x"]              = tree_cb("cut"),
  --["c"]              = tree_cb("copy"),
  --["p"]              = tree_cb("paste"),
  --["[c"]             = tree_cb("prev_git_item"),
  --["]c"]             = tree_cb("next_git_item"),
  --["<BS>"]           = tree_cb("dir_up"),
  --["q"]              = tree_cb("close"),
--}

vim.g.nvim_tree_bindings = {
  { key = {"l", "o", "<2-LeftMouse>"}, cb = tree_cb("edit") },
  { key = {"<2-RightMouse>", "<CR>"},    cb = tree_cb("cd") },
  { key = "<C-v>",                        cb = tree_cb("vsplit") },
  { key = "<C-x>",                        cb = tree_cb("split") },
  { key = "<C-t>",                        cb = tree_cb("tabnew") },
  { key = "<",                            cb = tree_cb("prev_sibling") },
  { key = ">",                            cb = tree_cb("next_sibling") },
  { key = "P",                            cb = tree_cb("parent_node") },
  { key = "h",                            cb = tree_cb("close_node") },
  { key = "<Tab>",                        cb = tree_cb("preview") },
  { key = "K",                            cb = tree_cb("first_sibling") },
  { key = "J",                            cb = tree_cb("last_sibling") },
  { key = "I",                            cb = tree_cb("toggle_ignored") },
  { key = "z",                            cb = tree_cb("toggle_dotfiles") },
  { key = "R",                            cb = tree_cb("refresh") },
  { key = "a",                            cb = tree_cb("create") },
  { key = "d",                            cb = tree_cb("remove") },
  { key = "r",                            cb = tree_cb("rename") },
  { key = "<C-r>",                        cb = tree_cb("full_rename") },
  { key = "x",                            cb = tree_cb("cut") },
  { key = "c",                            cb = tree_cb("copy") },
  { key = "p",                            cb = tree_cb("paste") },
  { key = "y",                            cb = tree_cb("copy_name") },
  { key = "Y",                            cb = tree_cb("copy_path") },
  { key = "gy",                           cb = tree_cb("copy_absolute_path") },
  { key = "[c",                           cb = tree_cb("prev_git_item") },
  { key = "]c",                           cb = tree_cb("next_git_item") },
  { key = "<BS>",                            cb = tree_cb("dir_up") },
  { key = "q",                            cb = tree_cb("close") },
  { key = "g?",                           cb = tree_cb("toggle_help") },
}
